name: Docs
on:
  push:
    paths:
      - "docs/**"
    branches:
      - master
jobs:
  release:
    name: Deploy to gh-pages
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - name: Build and Deploy
        uses: grasilife/github-pages-deploy-action@master
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BASE_BRANCH: master
          BRANCH: gh-pages
          FOLDER: docs/.vuepress/dist # The folder the action should deploy.
          BUILD_SCRIPT: npm install && npm run docs:build
